ethereum_rpc = "https://1rpc.io/holesky"
drosera_rpc = "https://relay.testnet.drosera.io"

[traps]

[traps.player1]
path = "/root/traps/Trap.json"
response_contract = "0xDB5A74A6805DC7570293f56467621B40c706510e"
response_function = "play(uint256)"
min_number_of_operators = 1
max_number_of_operators = 2
cooldown_period_blocks = 4
block_sample_size = 1
private_trap = true
whitelist = ["0x09D450BDD08B7eA3E04BCAec52A60124ad386Fca"]
address="0x078c96e344Ae34EdC38CA0Cc2FF0d735F2045044"
